### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by vincentcox-work** [GISDev01/security-ssid-abi#2]
I get the following error when I run` ./run.sh -i wlan0mon`

```
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    from packet_processing import packet_processor
  File "/root/security-ssid-abi/packet_processing/packet_processor.py", line 9, in <module>
    from db import influx
  File "/root/security-ssid-abi/db/__init__.py", line 12, in <module>
    influxdb_client.create_database(settings.INFLUX_DB)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 488, in create_database
    self.query("CREATE DATABASE \"%s\"" % dbname)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 339, in query
    expected_response_code=expected_response_code
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 246, in request
    raise e
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.99.1.26', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22securityssid%22&db=securityssid (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd307b0b110>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
### info

```
iwconfig
wlan0mon  IEEE 802.11  Mode:Monitor  Frequency:2.457 GHz  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          
eth0      no wireless extensions.

lo        no wireless extensions.
```

**Comment by GISDev01** [comment]
Looks like it can't connect to the influxdb database. Do you have influxdb running and binded to that specific IP in the error?

To be more specific, in the file .\security_ssid\settings.py - you'll want to set the IP or hostname of your InfluxDB box. I will update the readme to include this during the initial setup. Thanks for reporting it.

**Comment by vincentcox-work** [comment]
It was indeed influxdb that needed to run. Thank you!
