### ISSUE TITLE
No such file or directory: '/root/security-ssid-abi/mac_parser/manuf'

### ISSUE THREAD

**Issue by vincentcox-work** [GISDev01/security-ssid-abi#3]
Do you know what could cause the following error:

```
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    from packet_processing import packet_processor
  File "/root/security-ssid-abi/packet_processing/packet_processor.py", line 15, in <module>
    mac_parser_ws = manuf.MacParser()
  File "/root/security-ssid-abi/mac_parser/manuf.py", line 68, in __init__
    self.refresh()
  File "/root/security-ssid-abi/mac_parser/manuf.py", line 83, in refresh
    with io.open(os.path.join(os.getcwd(), 'mac_parser', manuf_name), "r", encoding="utf-8") as read_file:
IOError: [Errno 2] No such file or directory: '/root/security-ssid-abi/mac_parser/manuf'
```
Thanks in advance!

**Comment by GISDev01** [comment]
It's a Wireshark database of MAC addresses, and it is updated often so I leave it out of the repo. 
You can find the latest version here:
https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf

I will add this to the readme.
